name: Publish flake

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: The existing tag to publish
        type: string
        required: true

jobs:
  publish-to-flakestry:
    name: "Publish to flakestry.dev"
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: flakestry/flakestry-publish@main
        with:
          version: "${{ inputs.tag || github.ref_name }}"


  publish-to-flakehub:
    name: "Publish to flakehub.com"
    runs-on: "ubuntu-22.04"
    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - uses: "actions/checkout@v3"
        with:
          ref: "${{ (inputs.tag != null) && format('refs/tags/{0}', inputs.tag) || '' }}"

      - uses: "DeterminateSystems/nix-installer-action@main"

      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "public"
          name: "imincik/geospatial-nix"
          tag: "${{ inputs.tag }}"