name: Test custom packages build

on:
  workflow_call:

env:
  NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          # - macos-11

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install nix
      uses: cachix/install-nix-action@v25

    - name: Setup cachix
      uses: cachix/cachix-action@v14
      with:
        name: geonix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Point Geonix input to the local source code directory
      run: |
        sed -i.orig "s|geonix.url = \".*\";|geonix.url = \"path:${GITHUB_WORKSPACE}\";|" flake.nix
      working-directory: tests/shells

    - name: Flake check
      run: >
        nix flake check --impure --no-build --accept-flake-config
      working-directory: tests/shells

    - name: Generate override template file
      run: |
        nix run ${GITHUB_WORKSPACE}#geonixcli -- override

        git add *
      working-directory: tests/shells

    - name: Enable customizePackages function
      run: |
        sed -i.orig "s|^  geopkgs = inputs.geonix|# geopkgs.inputs.geonix|" geonix.nix

        sed -i.orig "/CUSTOMIZE-PACKAGES-START/,/CUSTOMIZE-PACKAGES-END/ s|#||" geonix.nix
      working-directory: tests/shells


    # Custom GDAL
    - name: Apply custom GDAL patch to override template file
      run: |
        patch -u overrides.nix -i gdal.patch
      working-directory: tests/shells

    - name: Flake check
      run: >
        nix flake check --impure --no-build --accept-flake-config
      working-directory: tests/shells

    - name: Build and test patched GDAL package
      run: |
        nix develop --impure --accept-flake-config --command gdalinfo --help | grep "Usage: gdalinfo (patched)"
      working-directory: tests/shells
